_weaponfactory =

[
"RH_tt33",
"RH_8Rnd_762_tt33",
"RH_p38",
"RH_8Rnd_9x19_p38",
"RH_uspm",
"RH_15Rnd_9x19_usp",
"RH_12Rnd_45cal_usp",
"RH_browninghp",
"RH_13Rnd_9x19_bhp",
"RH_mk22",
"RH_10Rnd_22LR_mk2",
"RH_m9c",
"Rnd_9x19_M9",
"RH_anacg",
"RH_6Rnd_44_Mag",
"RH_python",
"RH_6Rnd_357_Mag",
"C1987_P99_black",
"15Rnd_9x19_p99",
"RH_m1911old",
"RH_8Rnd_45cal_m1911",
"RH_bull",
"RH_6Rnd_44_Mag",
"C1987_P99_black_sd",
"JoC_Flitsche",
"JoC_FlitschMag",
"MBG_Compound_Bow",
"MBG_Arrow_N"
];

_terrorfactoryitems = 

[
"RH_oc14",
"RH_rk95sd",
"RH_aks47",
"RH_aks47b",
"AK_47_S",
"RH_akm",
"RPG18",
"RPG18_mag",
"RH_m14maf",
"Lada2_TK_CIV_EP1",
"GAZ_Vodnik"
];

_vehiclefactory =

[
"MMT_USMC",
"Volha_1_TK_CIV_EP1",
"S1203_TK_CIV_EP1",
"civic",
"Car_hatchback",
"VWGolf",
"Car_Sedan",
"SkodaBlue",
"Skodared",
"lada1",
"lada2",
"ibr_van_BNK",
"LandRover_TK_CIV_EP1",
"datsun1_civil_3_open",
"hilux1_civil_3_open",
"UAZ_Unarmed_TK_CIV_EP1",
"oldtruck",
"Tractor",
"a2l_impala_blue",
"a2l_impala_red",
"440cuda",
"roadrunner",
"roadrunner2",
"CHEVROLET_CAMARO_SS_396",
"chevrolet_chevelle",
"cuda",
"hemicuda",
"cd71hm",
"barcuda",
"fury",
"FORD_MUSTANG_SHELBY_COBRA",
"FORD_MUSTANG_SHELBY_COBRA1",
"FORD_MUSTANG_SHELBY_COBRA2",
"FORD_MUSTANG_SHELBY_COBRA3",
"FORD_GT",
"monaco_grey",
"monaco_blue",
"monaco_white",
"monaco_green",
"monaco_red",
"challenger_grey",
"challenger_blue",
"challenger_yellow",
"challenger_pink",
"challenger_white",
"challenger_green",
"challenger_red",
"challenger_orange",
"cl_charger",
"cl_charger_black",
"il_charger_blue",
"il_charger_black",
"il_charger_red",
"il_charger_orange",
"MAZDA_RX_7",
"MAZDA_RX_71",
"MAZDA_RX_72",
"MAZDA_RX_73",
"MAZDA_RX_75",
"MAZDA_RX_74",
"MAZDA_MAZDASPEED_3",
"tahoe_grey",
"tahoe_darkblue",
"tahoe_blue",
"tahoe_yellow",
"tahoe_white",
"tahoe_green",
"tahoe_black",
"tahoe_orange",
"tahoe_pink",
"tahoe_darkblue_cb",
"tahoe_grey_cb",
"tahoe_blue_cb",
"tahoe_yellow_cb",
"tahoe_pink_cb",
"tahoe_white_cb",
"tahoe_green_cb",
"tahoe_black_cb",
"tahoe_orange_cb",
"tcg_hrly",
"tcg_hrly_coco",
"tcg_hrly_demon",
"tcg_hrly_limited",
"tcg_hrly_orig1",
"tcg_hrly_gay",
"tcg_hrly_metal",
"tcg_hrly_orig2",
"tcg_hrly_white",
"tcg_hrly_blue",
"tcg_hrly_red",
"TT650_TK_CIV_EP1",
"TT650_Ins",
"TT650_Civ",
"ATV_CZ_EP1"
];

_vehiclefactory2 =

[
"CHRYSLER_300",
"RENAULT_CLIO_SPORT_V6",
"SUBARU_IMPREZA_WRX_STI_AWD",
"SUBARU_IMPREZA_STI_AWD",
"FIAT_PUNTO",
"ALFA_ROMEO_BRERA",
"NISSAN_240SX_SE",
"PONTIAC_GTO_6",
"240GD",
"MustangGTRyellow_MLOD",
"Convertible_MLOD",
"FORD_SHELBY_GT",
"CHRYSLER_W_limmo",
"CORVETTE_Z06",
"INFINITI_G35",
"MERCEDES_BENZ_CLK_500",
"MERCEDES_BENZ_SL_65_AMG",
"JAGUAR_XK",
"CADILLAC_CTS",
"CL_PORSCHE_997",
"CL_LAMBORGHINI_GT3",
"KOENIGSEGG_CCX",
"KOENIGSEGG_CCX1",
"KOENIGSEGG_CCX2",
"KOENIGSEGG_CCX3",
"MCLAREN_F1",
"MERCEDES_BENZ_SLR",
"PORSCHE_997_GT3_RSR",
"PORSCHE_911_TURBO",
"PORSCHE_911_GT3_RS",
"LAMBORGHINI_MURCIELAGO",
"LAMBORGHINI_REVENTON",
"LAMBORGHINI_GALLARDO",
"MASERATI_MC12",
"JAGUAR_XK",
"BUGATTI_VEYRON",
"AUDI_TT_QUATTRO_S_LINE",
"AUDI_FSI_LE_MANS",
"PAGANI_ZONDA_F",
"ASTON_MARTIN_DB9",
"NISSAN_GTR_SPECV",
"NISSAN_GTR_SPECV1",
"NISSAN_GTR_SPECV2",
"NISSAN_GTR_SPECV3",
"NISSAN_350Z",
"NISSAN_370Z",
"NISSAN_370Z1",
"NISSAN_370Z2",
"NISSAN_370Z3",
"NISSAN_370Z4",
"NISSAN_SKYLINE_GT_R_Z",
"NISSAN_SKYLINE_GT_R_Z1",
"NISSAN_SKYLINE_GT_R_Z2",
"NISSAN_SKYLINE_GT_R_Z3",
"cl_del_mackr",
"cl_trucktest_mackr",
"cl_flatbed_mackr",
"Ural_TK_CIV_EP1",
"V3S_Open_TK_CIV_EP1",
"V3S_TK_EP1",
"UralOpen_CDF",
"KamazOpen",
"Ural_CDF",
"cooter",
"il_towtruck",
"cl_quaddescammo",
"cl_green",
"cl_quadred",
"cl_quadsaftysteel",
"cl_quadyellow",
"cl_blue2",
"cl_chark",
"cl_dirtyred"
];

_vehiclefactory3 =

[
"raptor_black",
"raptor_grey",
"raptor_blue",
"raptor_yellow",
"raptor_pink",
"raptor_white",
"raptor_green",
"raptor_red",
"raptor_orange",
"Cherokee_black",
"Cherokee_grey",
"Cherokee_blue",
"Cherokee_yellow",
"Cherokee_pink",
"Cherokee_white",
"Cherokee_green",
"Cherokee_red",
"Cherokee_orange",
"rangerover_black",
"rangerover_blue",
"rangerover_yellow",
"rangerover_pink",
"rangerover_white", 
"rangerover_green",
"rangerover_red",
"rangerover_orange",
"s331_black",
"s331_grey",
"s331_blue",
"s331_yellow",
"s331_pink",
"s331_white",
"s331_green",
"s331_red",
"s331_orange",
"h1_black",
"h1_grey",
"h1_blue",
"h1_yellow",
"h1_pink",
"h1_white",
"h1_green",
"h1_red",
"transit_pink",
"tcg_taurus_civ1",
"tcg_taurus_civ2",
"tcg_taurus_civ3",
"tcg_taurus_civ4",
"tcg_taurus_civ5",
"tcg_taurus_civ6",
"il_fordcv_white",
"il_fordcv_grey",
"il_fordcv_black",
"il_fordcv_darkblue",
"il_fordcv_maroon",
"il_fordcv_sandstone",
"m5_red",
"m5_grey",
"m5_blue",
"m5_c_green",
"m5_c_black",
"m5_c_white",
"BMW_M6",
"BMW_M3_GTR",
"BMW_M3",
"BMW_M3_RALLY",
"BMW_135I",
"tcg_bmw_m3",
"tcg_bmw_m3_hamwhite",
"tcg_bmw_m3_c1",
"tcg_bmw_m3_c3",
"tcg_bmw_m3_c4",
"tcg_bmw_m3_c5",
"tcg_bmw_m3_c6",
"tcg_bmw_m3_c7",
"tcg_bmw_m3_c8",
"tcg_bmw_m3_c9",
"tcg_aprilia_blue",
"tcg_aprilia_yellow",
"tcg_aprilia_white",
"tcg_aprilia_green",
"tcg_aprilia_red",
"tcg_aprilia_black",
"tcg_aprilia_black_2",
"tcg_aprilia_blue_2",
"tcg_aprilia_blue_4",
"tcg_aprilia_blue_5",
"tcg_aprilia_cyan",
"tcg_aprilia_green_3",
"tcg_aprilia_orange",
"tcg_aprilia_red_1",
"tcg_aprilia_red_2",
"tcg_aprilia_white_2",
"tcg_aprilia_yellow_2"
];

_pickupfactory = 
[
"il_silverado_black",
"il_silverado_red",
"il_silverado_orange",
"il_silverado_selvo",
"il_silverado_white",
"tcg_suburban_red",
"tcg_suburban_yellow",
"tcg_suburban_grey",
"tcg_suburban_white",
"tcg_suburban_green",
"suburban_blue",
"suburban_black",
"suburban_maroon",
"suburban_sandstone",
"suburban_grey",
"suburban_white",
"f350_red",
"f350_blue",
"f350_pink",
"f350_white",
"f350_black"
];



_itemfactory =

[
"Land_ladder_half",
"MBG_Compound_Bow",
"MBG_Arrow_N",
"JoC_Flitsche",
"JoC_FlitschMag",
"RH_m9",
"Rnd_9x19_M9",
"RH_m1911",
"RH_8Rnd_45cal_m1911",
"revolver_EP1",
"revolver_gold_EP1",
"Rnd_45ACP",
"RH_usp",
"RH_15Rnd_9x19_usp",
"RH_uspm",
"RH_12Rnd_45cal_usp",
"RH_python",
"RH_6Rnd_357_Mag",
"Binocular",  
"NVGoggles",
"GPS",
"handy",
"reparaturkit",
"kanister",
"lockpick",
"medikit",
"lighter",
"fernzuender",
"fishingpole",
"Fence_corrugated_plate",
"FoldChair",
"Land_Chair_EP1",
"Garbage_can",
"MAP_washing_machine",
"woodchair",
"SmallTV",
"FoldTable",
"SmallTable",
"supgrade1",
"supgrade2"

];

_lilcubafactory = 

[
"RH_anacg",
"RH_6Rnd_44_Mag",
"RH_python",
"RH_6Rnd_357_Mag",
"RH_deagle",
"RH_7Rnd_50_AE",
"RH_g17",
"RH_19Rnd_9x19_g18",
"RH_m1911old",
"RH_8Rnd_45cal_m1911",
"RH_bull",
"RH_6Rnd_44_Mag",
"RH_tec9",
"RH_30Rnd_9x19_tec",
"RH_mp5kpdw",
"30rnd_9x19_MP5",
"RH_uzi",
"RH_uzig",
"RH_muzi",
"RH_9mm_32RND_Mag",
"RH_mp7",
"RH_46x30mm_40RND_Mag",
"RH_mp5kpdw",
"RH_mp5a4",
"RH_mp5a4RFX",
"RH_mp5a5ris",
"RH_mp5k",
"RH_mp7",
"RH_mp5kpdw",
"RH_tmpeot",
"rnd_9x19_MP5",
"RH_akm",
"30rnd_762x39_ak47",
"RH_aks47",
"RH_M16a1",
"30Rnd_556x45_Stanag",
"Huntingrifle",
"x_22_LR_17_HMR"
];

_airvehiclefactory =

[
"An2_1_TK_CIV_EP1",
"An2_2_TK_CIV_EP1",
"USEC_MAULE_M7_STD",
"gnt_piperwii",
"GNT_C185F",
"GNT_C185E",
"GNT_C185R",
"GNT_C185C",
"GNT_C185",
"kyo_ultralight",
"AH6X_EP1",
"CSJ_Gyroc",
"Mi17_Civilian",
"bd5j_civil_3",
"bd5j_civil_2",
"bd5j",
"GazelleUN",
"Gazelle",
"Gazelle1",
"Gazelle3",
"adf_as350",
"ibr_as350_specops",
"ibr_as350_jungle",
"tcg_bell206_3",
"tcg_bell206_4",
"tcg_bell206_2",
"tcg_bell206_5",
"tcg_bell206",
"MH6J_EP1",
"can_c130",
"airnz_C130",
"luf_c130",
"qantas_C130",
"A320MPA",
"SantaSleigh"
];

_tairfactory = ["Mi17_TK_EP1","Pickup_PK_TK_GUE_EP1","UAZ_MG_TK_EP1","Offroad_DSHKM_TK_GUE_EP1"];

_alcoholfactory = ["beer","beer2","vodka","smirnoff","wiskey","wine","wine2"];

_resourcefactory=[
"woodchair",
"diamondring",
"diamondbroach",
"diamondnecklace",
"steel",
"blackpowder",
"glass",
"plastic"
];

_resourceweaponsfactory=[

];

//_Baekerei	  = ["Apfelkuchen","Bread"];

vehiclequeue  	= [];
vehiclequeue2  	= [];
vehiclequeue3  	= [];
tvehiclequeue 	= [];
weaponqueue 	= [];
itemqueue 	= [];
avehiclequeue	= [];
tavehiclequeue	= [];
alcoholfactoryqueue  = [];
terrorfactoryitemsqueue = [];
//Baekereiqueue  = [];
resourcequeue = [];
resourceweapqueue = [];
airvehiclequeue  	= [];

INV_ItemFabriken =

[
[Vehiclefactory,"factory1","RONNE  Car Factory",dummyobj,vfacspawn,_vehiclefactory,250000,"Fabrikablage1", "vehiclequeue"],
[Vehiclefactory2,"factory2","Zoom Car Factory",dummyobj,vfacspawn2,_vehiclefactory2,250000,"Fabrikablage2", "vehiclequeue2"],
[Vehiclefactory3,"factory11","MzNiCh Factory",dummyobj,vfacspawn3,_vehiclefactory3,250000,"Fabrikablage11", "vehiclequeue3"],
[igunbox,"factory3","General Factory",igunbox,dummyobj,_itemfactory,150000,"Fabrikablage3", "itemqueue"],
[wfgunbox,"factory4","Weapon Factory",wfgunbox,dummyobj,_weaponfactory,600000,"Fabrikablage4", "weaponqueue"],
[lilcuba,"factory5","Lil Cuba Gun Factory",lilcuba,dummyobj,_lilcubafactory,500000,"Fabrikablage5", "tvehiclequeue"],
[tairshop,"factory6","Terrorist Vehicle Factory",dummyobj,tairspawn,_tairfactory,200000,"Fabrikablage6", "tavehiclequeue"],
[alcoholfactory,"factory7","Alcohol Factory",dummyobj,dummyobj,_alcoholfactory,10000,"Fabrikablage7", "alcoholfactoryqueue"],
[ressourcenfabrik_1,"factory9","ResourceFactory",dummyobj,dummyobj,_resourcefactory,10000,"Fabrikablage9","resourcequeue"],
[bmgunbox,"factory8","Black Market Factory",bmgunbox,bmcar,_terrorfactoryitems,1000000,"Fabrikablage8", "terrorfactoryitemsqueue"],
[resbox2,"factory10","ResourceweaponsFactory",resbox2,dummyobj,_resourceweaponsfactory,400000,"Fabrikablage10","resourceweapqueue"],
[helifac,"factory12","Tom's Air Factory",dummyobj,hfacspawn,_airvehiclefactory,200000,"Fabrikablage12", "airvehiclequeue"]
];

INV_Fabrikowner = [];

INV_FarmItemArray = 

[
//[[["fishingwhale",400]],"Whale",2,1,["Ship"]],
//[[["fishingbass",400]],"bass",15,4,["Ship"]],
//[[["fishingblowfish",200]],"blowfish",15,8,["Ship"]],
//[[["fishingherring",200]],"herring",15,8,["Ship"]],
//[[["fishingmackerel",200]],"mackerel",15,8,["Ship"]],
//[[["fishingblowfish1",200]],"blowfish",15,8,["Ship"]],
//[[["fishingherring1",200]],"herring",15,8,["Ship"]],
//[[["fishingmackerel1",200]],"mackerel",15,8,["Ship"]],
//[[["cocafield",30]],"Unprocessed_cocaine",15,4,["Man"]],
[[["marifield",50]],"Unprocessed_marijuana",15,4,["Man"]],
[[["lsdfield",30]],"Unprocessed_lsd",15,4,["Man"]],
[[["lsdfield_1",30]],"Unprocessed_lsd",15,4,["Man"]],
[[["lsdfield_2",30]],"Unprocessed_lsd",15,4,["Man"]],
//[[["heroinfield",30]],"Unprocessed_heroin",15,4,["Man"]],
[[["Diamond",20]],"Diamond rock",15,1,["Man"]],
[[["Diamond2",20]],"Diamond rock",15,1,["Man"]],
[[["farmarea1",90]],"getreide",20,10,["tractor","oldtruc2","oldtruc2a"]],
[[["farmarea2",90]],"getreide",20,10,["tractor","oldtruc2","oldtruc2a"]],
[[["farmarea3",90]],"getreide",20,10,["tractor","oldtruc2","oldtruc2a"]],
[[["farmarea7",70]],"straw",20,10,["tractor","oldtruc2","oldtruc2a"]],
[[["farmarea8",70]],"straw",20,10,["tractor","oldtruc2","oldtruc2a"]],
[[["farmarea9",70]],"straw",20,10,["tractor","oldtruc2","oldtruc2a"]],
[[["woodarea",70]],"wood",15,5,["Man"]],
[[["woodarea1",70]],"wood",15,5,["Man"]],
[[["sandarea",70]],"sand",15,5,["Man"]],
[[["sandarea1",70]],"sand",15,5,["Man"]],
[[["apfelfeld1",50]],"apple",10,5,["Man"]],
[[["apfelfeld2",50]],"apple",10,5,["Man"]],
[[["dirtys1",50]],"trash",10,5,["streetsweeper","a2l_dot_f350_utility"]],
[[["dirtys2",50]],"trash",10,5,["streetsweeper"]],
[[["dirtys3",50]],"trash",10,5,["streetsweeper"]],
[[["dirtys4",50]],"trash",10,5,["streetsweeper","a2l_dot_f350_utility"]],
[[["dirtys5",50]],"trash",10,5,["streetsweeper"]],
[[["soccerfield",50]],"grass",10,6,["a2l_dot_f350_utility"]],
[[["dirtdig",50]],"dirt",10,6,["MBG_D7H_DES","MBG_D7H_CIV","MBG_D7H_GRN"]],
[[["dirtdig2",50]],"dirt",10,6,["MBG_D7H_DES","MBG_D7H_CIV","MBG_D7H_GRN"]],
[[["dirtdig3",50]],"dirt",10,6,["MBG_D7H_DES","MBG_D7H_CIV","MBG_D7H_GRN"]],
[[["nuke1",50]],"nuclear",10,6,["Man"]],
[[["nuke2",50]],"nuclear",10,6,["Man"]]
];

Miningarray = 

[
[["OilArea1",15],"Oil",12],
[["OilArea2",15],"Oil",12],
[["OilArea3",15],"Oil",12],
[["OilArea4",15],"Oil",12],
[["IronArea",30],"iron",12],
[["IronArea1",30],"iron",12],
[["GoldArea",15],"gold",12],
[["GoldArea1",15],"gold",12],
[["CopperArea",30],"copper",12],
[["CopperArea1",30],"copper",12],
[["CoalArea",30],"coal",12],
[["CoalArea1",30],"coal",12]
];

fishingarray =
[
[["fishingwhale",200], "whale",1],
[["fishingwhale1",200], "whale",1],
[["fishingblowfish",30], "blowfish",6],
[["fishingblowfish_1",30], "blowfish",6],
[["fishingblowfish_2",30], "blowfish",6],
[["fishingherring",30], "herring",6],
[["fishingherring_1",30], "herring",6],
[["fishingherring_2",30], "herring",6],
[["fishingmackerel",30], "mackerel",6],
[["fishingmackerel_1",30], "mackerel",6],
[["fishingmackerel_2",30], "mackerel",6],
[["fishingbass",100], "bass",6],
[["fishingbass_1",100], "bass",6],
[["fishingbass_2",100], "bass",6],
[["percharea",30], "perch",6],
[["walleyearea",30], "walleye",6],
[["troutarea",30], "trout",6]
];

fishingarray1 = ["blowfish","herring","mackerel","bass","perch","walleye","trout"];

bodyarray = ["eyes","brain","liver","heart","kidney","bones","teeth"];