INV_Lizenzen = 

[
["mayorlic",dmv,"Licence de Gouverneur",1500000],
["boat",dmv,localize "STRS_license_boat",10000],
["fboat",dmv,"Permis de Ferry",20000],
["esul",atm5,"Entrainement de Pompier",0],
["esul",atm10,"Entrainement de Pompier",0],
["bus_license",truckshop,"Permis de Bus",15000],
["truck",truckshop,localize "STRS_license_truck",50000],
["taxi",taxishop,"Licence de Taxi",5000],
["car",dmv,localize "STRS_license_car",5000],
["car",dmv2,localize "STRS_license_car",5000],
["car",dmv3,localize "STRS_license_car",5000],
["oil",Oil_1,"Licence de Raffinage de Pétrole",25000],
["Baker",Bakery,"Licence de Boulanger",10000],
//["cooker",vending2,"Licence de Boucher",10000],
["cocaine ga1",gangarea1,"GA1 Licence de Transformation de la Cocaine",50000],
["lsd ga1",gangarea1,"GA1 Licence de Transformation du LSD",50000],
["heroin ga2",gangarea2,"GA2 Licence de Transformation de l'Heroine",50000],
["lsd ga2",gangarea2,"GA2 Licence de Transformation du LSD",50000],
["heroin ga3",gangarea3,"GA3 Licence de Transformation de l'Heroine",50000],
["marijuana ga3",gangarea3,"GA3 Licence de Transformation de la Marijuana",50000],
["heroin ga4",gangarea4,"GA4 Licence de Transformation de l'Heroine",50000],
["marijuana ga4",gangarea4,"GA4 Licence de Transformation de la Marijuana",50000],
["air",airshop,localize "STRS_license_air",35000],
["air",airshop4,localize "STRS_license_air",35000],
["comair",airshop3,"Licence de Commerce Aerien",100000],
//["gunprobationpistol",Licenseflag2,"Probation pistol license",20000],
["Pistollicense",gundealer1,"Licence de Pistolet",50000],
["riflelicense",vending2,"Licence de Chasse",20000],
["assassinlic",assassinshop,"Illegal Assassin Weapons Fee",70000],
//["engineer",terrorbox, "Bomb Training License",900000],
//["bomb",gundealer1,"FUll Auto Weapons Fee",200000],
["terror",terrorbox,"Acces au Marche Noir",800000],
["probator",copbasic2,localize "STRS_license_probator",2000],
["patrol_training",copbank,localize "STRS_license_coppatrol",50000],
["patrol_training",atm4,localize "STRS_license_coppatrol",50000],
//["response_training",copbank,localize "STRS_license_copresponse",100000],
["sobr_training",copswat,localize "STRS_license_copswat",250000],
//["cg_boat",copbank,"Entrainement au Patrouille en Bateau",1000],
["Donator_licence",Donatebuy,"Donateur License",31000000],
//["mafial",vip4shop,"Mafia invitation",1],
["towl",truckshop,"Licence de Remorquage",50000],
["air_support_training",copbank,localize "STRS_license_copairsupport",5000],
["millis",milp,"Licence Militaire de Police",5000],
["bounh",bhunt,"Licence de Chasseur de Prime",5000],
["pmcl",pmc,"Licence de PMC's",5000000],
["vipcl",VIPcop,"Licence VIP de Police",31000000],
["viptl",terrorvip,"Acces au Marche Noir VIP",800000],
["cgl",cgweapons,"Entrainement Garde-Cote",2500],
["cgawl",cgweapons,"Entrainement Avancer Garde-Cote",5000],
["cgml",cgweapons,"Licence de Ravitailleur de Cote",10000],
["unweapons",unweapons,"Licence d'armes des United Nation",30000],
["unbasic",unbasic,"Licence Basique des United Nation",25000],
["pirate",pirategearbox,"License Pirate",150000]



];

INV_LizenzOwner = [];