INV_Lizenzen = 

[
["mayorlic",dmv,"Governors license",100000],
["boat",dmv,localize "STRS_license_boat",1500],
["fboat",dmv,"Ferry Captain License",2500],
["esul",atm5,"Fire Rescue Training",100],
["esul",atm10,"Fire Rescue Training",100],
["bus_license",truckshop,"Bus License",1000],
["truck",truckshop,localize "STRS_license_truck",5000],
["taxi",taxishop,"Taxi License",5000],
["car",dmv,localize "STRS_license_car",2500],
["car",dmv2,localize "STRS_license_car",2500],
["car",dmv3,localize "STRS_license_car",2500],
["oil",Oil_1,"Oil processor's license",30000],
["Baker",Bakery,"Baker's license",10000],
//["cooker",vending2,"Meat Processing license",10000],
["cocaine ga1",gangarea1,"GA1 cocaine Drug processor's license",35000],
["lsd ga1",gangarea1,"GA1 LSD Drug processor's license",35000],
["heroin ga2",gangarea2,"GA2 Heroin Drug processor's license",35000],
["lsd ga2",gangarea2,"GA2 LSD Drug processor's license",35000],
["heroin ga3",gangarea3,"GA3 Heroin Drug processor's license",35000],
["marijuana ga3",gangarea3,"GA3 Marijuana Drug processor's license",35000],
["heroin ga4",gangarea4,"GA4 Heroin Drug processor's license",35000],
["marijuana ga4",gangarea4,"GA4 Marijuana Drug processor's license",35000],
["air",airshop,localize "STRS_license_air",35000],
["air",airshop4,localize "STRS_license_air",35000],
["comair",airshop3,"Commercial Air License",100000],
//["gunprobationpistol",Licenseflag2,"Probation pistol license",20000],
["Pistollicense",gundealer1,"Pistol license",50000],
["riflelicense",vending2,"Hunting License",20000],
["assassinlic",assassinshop,"Illegal Assassin Weapons Fee",70000],
//["engineer",terrorbox, "Bomb Training License",900000],
//["bomb",gundealer1,"FUll Auto Weapons Fee",200000],
["terror",terrorbox,"Black Market Access",800000],
["probator",copbasic2,localize "STRS_license_probator",2000],
["patrol_training",copbank,localize "STRS_license_coppatrol",500],
["patrol_training",atm4,localize "STRS_license_coppatrol",500],
//["response_training",copbank,localize "STRS_license_copresponse",1000],
["sobr_training",copswat,localize "STRS_license_copswat",2500],
//["cg_boat",copbank,"PD Patrol Boat Training",1000],
["Donator_licence",Donatebuy,"Donator License",500000000],
//["mafial",vip4shop,"Mafia invitation",1],
["towl",truckshop,"Towing License",50000],
["air_support_training",copbank,localize "STRS_license_copairsupport",5000],
["millis",milp,"Military Police License",5000],
["bounh",bhunt,"Bounty Hunter License",5000],
["pmcl",pmc,"PMC License",150000],
["vipcl",VIPcop,"Cop VIP 4 License",500000],
["viptl",terrorvip,"Black Market VIP 4",800000],
["cgl",cgweapons,"Coast Guard Training",2500],
["cgawl",cgweapons,"Coast Guard Advance Training",5000],
["cgml",cgweapons,"Coast Mother Ship Licence",10000],
["unweapons",unweapons,"United Nation Weapons Licence",30000],
["unbasic",unbasic,"United Nation Basic Licence",25000],
["pirate",pirategearbox,"Jolly Roger Flag",150000]


];

INV_LizenzOwner = [];